function writeplyfaces(points, rgb, faces, filename)

    file = fopen(filename,'w');
    
    text = sprintf(['ply\n' ...
                    'format ascii 1.0\n' ...
                    'element vertex %s\n' ...
                    'property float x\n' ...
                    'property float y\n' ...
                    'property float z\n' ...
                    'property uchar red\n' ...
                    'property uchar green\n' ...
                    'property uchar blue\n' ...
                    'element face %s\n'...
                    'property list uchar int vertex_indices\n' ...
                    'end_header\n'], ...
                    num2str(size(points,1)), num2str(size(faces,1)));
     fprintf(file, text);
     
     data = [points round(rgb)];
% 	 data = points;
%      dlmwrite(filename,num2str(data),'-append','delimiter','')
%      fprintf(file, num2str(data));
     fprintf(file, '%f %f %f %d %d %d\n', data');
     fprintf(file, '3 %d %d %d\n', faces');
     fclose(file);
%      dlmwrite(filename,[points double(rgb)],'-append','delimiter','\t','precision','%.4f')
end