function writeplynormals(points, normals, faces, filename)

    file = fopen(filename,'w');
    
    text = sprintf(['ply\n' ...
                    'format ascii 1.0\n' ...
                    'element vertex %s\n' ...
                    'property float x\n' ...
                    'property float y\n' ...
                    'property float z\n' ...
                    'property float nx\n' ...
                    'property float ny\n' ...
                    'property float nz\n' ...
                    'element face %s\n'...
                    'property list uchar int vertex_indices\n'...
                    'end_header\n'], num2str(size(points,1)), num2str(size(faces,1)));
     fprintf(file, text);
     
     data = [points normals];
%      dlmwrite(filename,num2str(data),'-append','delimiter','')
     fprintf(file,'%f %f %f %f %f %f\n',data');
     fprintf(file,'3 %d %d %d\n',faces');
     
     fclose(file);

end